sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QfS1p3ZTwKr0f2khSY3JPsl8/Cl6cngtnIqCgCLi9qGFAa2b2SsoEQ6EMBC048SmS223j3v3q+pxu+jyQuXHVdr1dy8QEklNBLu4h50sUXbyz9OU4+Jr04bhPW67BBz036FFccLqQR+Q1CxGtC1+O2EAyT8GN8iPricAVPk03joxlYE7nd252KqH5R3afw7X5lhWpRnEbW6jmvzyUF8LY//5ruyWgk+w9L5p5FTksl6hOK0Go3aJZSBAZK885qEWR4cX5aN9/RzwzydzZLdMP/UNVxa+MdII6rLnEgfEZhr+0VrbFIZ6B2PwwizZCGbd+Fv3rRVZorkcPhOK2qZX3RGbvu7FNTBon7U7pCAI9BMAEH3auldhlpgsjaZ7Rb/voI58yZWuYmr32dkqABilFXTCmeVul0Jwv5ywnEj/CN3RM1lUAI6LeSTRDSMjwxI3wEKbkWJKABKNlKvXeLj/GLAdFd7w9ambvg5pQ50T8He6gOShl9p/BUUQzOwbjvXt2z7bv2bXrLYPtwn+WNLWaD6e4hPNPRSrvOebY3iHqmoIXnSfHifjLUI4Mir3+lLrFl2poRyx/K6GmzfZ7r9Nuik91uBsg1lAu/vtqOU9jXhxARUouWka/kRf8xy8+//nnncHshPZNpLybxJSdl/yRKxeKeRNNkHSRjF2xzpRM3w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/My-Ten-Years-Imprisonment_2792
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy